name: Boop
"on":
  issues:
    types:
      - opened
  workflow_dispatch: {}
jobs:
  boop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - run: npm ci
      - run: node action.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
